const {test}=require('node:test'),assert=require('node:assert/strict');
const {BOT_PROFILES,seededRandom,createBotTemperament,chooseBotDecision}=require('./bots');
const {createGameServer}=require('./server');
test('health identifies the loaded bot strategy and only exposes a valid public commit SHA',async t=>{for(const releaseCommit of ['','not-a-public-sha','a'.repeat(40)]){const g=createGameServer({releaseCommit});await new Promise(r=>g.server.listen(0,'127.0.0.1',r));try{const s=await(await fetch('http://127.0.0.1:'+g.server.address().port+'/health')).json();assert.equal(s.botStrategyVersion,'bounded-randomness-v1');assert.equal(s.commit,releaseCommit==='a'.repeat(40)?releaseCommit:null);assert.deepEqual(Object.keys(s).sort(),['botStrategyVersion','commit','ok']);}finally{await new Promise(r=>g.server.close(r));}}});
const players=n=>Array.from({length:n},(_,i)=>({seat:i+1,score:0}));
function decision(profile,seed,extra={}){const random=seededRandom(seed),temperament=createBotTemperament(random);return chooseBotDecision({seat:2,profile,players:players(5),history:[],stage:0,temperament,...extra},random);}
test('per-game variation is bounded, immutable, reproducible and leaves four identities unchanged',()=>{const original=JSON.stringify(BOT_PROFILES);for(let seed=0;seed<64;seed++){const t=createBotTemperament(seededRandom(seed));assert.deepEqual(t,createBotTemperament(seededRandom(seed)));assert.ok(t.priorShift>=-4&&t.priorShift<=4);assert.ok(t.riskScale>=.9&&t.riskScale<=1.1);assert.ok(t.collisionScale>=.9&&t.collisionScale<=1.1);assert.ok(t.pressureScale>=.85&&t.pressureScale<=1.15);assert.ok(t.choiceWindow>=2&&t.choiceWindow<=6);assert.ok(t.exploration>=.08&&t.exploration<=.18);assert.ok(Object.isFrozen(t)&&Object.isFrozen(t.weightScales));for(let p=0;p<4;p++)assert.deepEqual(decision(p,seed),decision(p,seed));}assert.equal(JSON.stringify(BOT_PROFILES),original);});
test('different seeds vary openings while intuition, reasoning and deep calculation remain ordered',()=>{const samples=BOT_PROFILES.map((_,p)=>Array.from({length:32},(_,s)=>decision(p,s+1).value));const means=samples.map(a=>a.reduce((s,v)=>s+v,0)/a.length);for(const row of samples)assert.ok(new Set(row).size>=4,JSON.stringify(row));assert.ok(means[0]>means[1]+3&&means[1]>means[2]+3,JSON.stringify(means));});
test('all stages and danger scores produce legal integers; exact zero counterplay remains intact across seeds',()=>{for(let seed=1;seed<=12;seed++)for(let p=0;p<4;p++)for(let stage=0;stage<4;stage++){const roster=players(5-stage).map(v=>({...v,score:v.seat===2?-9:0}));const history=Array.from({length:8},()=>({target:0,values:roster.map(v=>({seat:v.seat,value:0}))}));const d=decision(p,seed,{players:roster,history,stage});assert.ok(Number.isInteger(d.value)&&d.value>=0&&d.value<=100);assert.equal(d.tactic,null);if(stage===3)assert.equal(d.value,100);if(stage===1){const result=require('./round').evaluateRound(roster.map(v=>({seat:v.seat,value:v.seat===2?d.value:0})),stage);assert.ok(result.winners.some(v=>v.seat===2));}}});
test('public evidence adapts; hidden current submissions and foreign plans are never read',()=>{for(let p=0;p<4;p++){const roster=players(5);for(const person of roster)Object.defineProperty(person,'value',{get(){throw Error('hidden value read');}});const history=v=>Array.from({length:8},()=>({target:v*.8,values:roster.map(a=>({seat:a.seat,value:v}))}));const input={players:roster,history:history(10)};Object.defineProperty(input,'currentSubmissions',{get(){throw Error('private submissions read');}});const low=decision(p,90,input).value,high=decision(p,90,{players:roster,history:history(70)}).value;assert.ok(high>low+20);}});
test('server retains one private temperament per game, seeds plans reproducibly and precommits before human input',async t=>{async function game(){let now=1000000,seed=600;const g=createGameServer({now:()=>now,botSeed:()=>seed++});await new Promise(r=>g.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>g.server.close(r)));const base='http://127.0.0.1:'+g.server.address().port,headers={'Content-Type':'application/json',Authorization:'Bearer '+'a'.repeat(48)};const post=async(route,body)=>{const r=await fetch(base+route,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});assert.ok(r.ok);return r.json();};const s=await post('/api/solo',{name:'合成测试'});const room=g.rooms.get(s.code);return {g,room,post,path:'/api/rooms/'+s.code,advance:ms=>now+=ms};}const a=await game(),b=await game();let saved;for(let round=1;round<=2;round++){const views=await Promise.all([a,b].map(g=>g.post(g.path+'/ready',{round:round-1})));const plans=g=>g.room.players.slice(1).map(p=>p.plan.value);assert.deepEqual(plans(a),plans(b));if(round===1)saved=a.room.players.slice(1).map(p=>p.temperament);else a.room.players.slice(1).forEach((p,i)=>assert.equal(p.temperament,saved[i]));for(const view of views)assert.ok(!/temperament|botRandom|priorShift|choiceWindow/.test(JSON.stringify(view)));for(const g of[a,b]){const before=plans(g);await g.post(g.path+'/submit',{round,value:round===1?100:5});assert.deepEqual(plans(g),before);g.advance(7000);g.g.settle(g.room); // bots submit on the following request's advance
await g.post(g.path);g.advance(24000);}}});


